[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  branch = "master"
  name = "github.com/spf13/cobra"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/viper"

[[constraint]]
  branch = "master"
  name = "github.com/spf13/afero"

[[constraint]]
  branch = "master"
  name = "github.com/dustin/go-humanize"


